### ISSUE TITLE
WCM don't save selected values

### ISSUE THREAD

**Issue by formalyknownasMIWI** [wacon-internet-gmbh/wacon_cookie_management#38]
Iam testing the WCM for production use.
All works fine with this great extension except only one problem:
the individuell cookie value won't save.
When i set a cookie group (include the cookies automatically) it works like a charm.
But if i set only one cookie in a cookie group for example to true and save it - the next time i open the management the value is set to false. So my change are ignored...
Any hints whats going wrong?
We work with Typo3 10.4
![wcm](https://user-images.githubusercontent.com/26787007/186620516-f5a4f2b7-6cfa-4c02-9d5d-d167719880ef.png)
.

**Comment by kuschmitt** [comment]
Please check branch update-setcookie-individuell. Does this solve the problem?

**Comment by formalyknownasMIWI** [comment]
Is there a special form to update/install the update-setcookie-individuell branch?
With Extension.Manager i get following error:
![image](https://user-images.githubusercontent.com/26787007/186882457-e64d1e84-f35b-4335-9966-2fc423e7eb64.png)
The installed version is 3.2.3 the branch version is 3.2.12 ...

**Comment by PKuhlmay** [comment]
Hi @formalyknownasMIWI 
There is no special form to do this.
Did you get this message while uploading the zip file from GitHub into your Extension Manager?
Because I get the same error and I am not sure yet if this is a bug inside TYPO3 or inside our extension.
You could also try to copy the content of the extension into the path typo3conf/ext/wacon_cookie_management inside your TYPO3 installation. This would override the "old" extension but I only recommend this, if you know what you are doing and in a develop installation, not in the production/live website. Otherwise your installation could be broken.

**Comment by formalyknownasMIWI** [comment]
Hi @PKuhlmay 
correct i get this error if i would upload with extension-manager.
Now i manually copied the files to typo3 like your advice.
The result is: nothing is broken and now the selected values would save correctly!
Now it runs like a charm! Thank you very much!
